### ISSUE TITLE
'16' constant value in Eq.(4)

### ISSUE THREAD

**Issue by shawrby** [Fusion-Goettingen/linearJPDA#1]
Hi, I would like to thank you for a wonderful paper.

I have a question about the code you implemented.

What does the value '16' mean? And how do I tune it?

```
for m = 1:M
     if (meas(:,m)'-r(n,1:2))*Cy(:,:,n)^-1*(meas(:,m)-r(n,1:2)') < 16
          G(n,m) = mvnpdf(meas(:,m),r(n,1:2)',Cy(:,:,n));
     end
end
```

**Comment by ShishanYang** [comment]
> Hi, I would like to thank you for a wonderful paper.
> 
> I have a question about the code you implemented.
> 
> What does the value '16' mean? And how do I tune it?
> 
> ```
> for m = 1:M
>      if (meas(:,m)'-r(n,1:2))*Cy(:,:,n)^-1*(meas(:,m)-r(n,1:2)') < 16
>           G(n,m) = mvnpdf(meas(:,m),r(n,1:2)',Cy(:,:,n));
>      end
> end
> ```

Hi, thank you for your interest in our work.
The condition of if clause is gating using Mahalanobis distance. It means only the predicted likelihoods of measurements lying in 4\sigma are calculated.

**Comment by shawrby** [comment]
Thanks for your fast reply!
I'm currently simulating with an expanded object, and the shape keeps getting smaller.
Am I missing something? 
![image](https://user-images.githubusercontent.com/54407464/149073764-5bbbfcdb-7a57-41f8-b5aa-771d2c7f5ef0.png)

**Comment by shawrby** [comment]
> > Hi, I would like to thank you for a wonderful paper.
> > I have a question about the code you implemented.
> > What does the value '16' mean? And how do I tune it?
> > ```
> > for m = 1:M
> >      if (meas(:,m)'-r(n,1:2))*Cy(:,:,n)^-1*(meas(:,m)-r(n,1:2)') < 16
> >           G(n,m) = mvnpdf(meas(:,m),r(n,1:2)',Cy(:,:,n));
> >      end
> > end
> > ```
> 
> Hi, thank you for your interest in our work. The condition of if clause is gating using Mahalanobis distance. It means only the predicted likelihoods of measurements lying in 4\sigma are calculated.

**Comment by shawrby** [comment]
Based on your wonderful research papers and kind replies, I have developed our data-driven multi-object tracking algorithm.
If there is an opportunity, I would like to study with you.
Thank you again.
