### ISSUE TITLE
Coordinate System requirement for estimating the shape parameters

### ISSUE THREAD

**Issue by boazMgm** [Fusion-Goettingen/linearJPDA#2]
Hi,
In case the detections are coming from a moving sensor, for example:, mounted on a host vehicle,
and are given in the local coordinate system of the radar itself (or the host), will the algorithm work as it written as it is now or a modification is needed?
The simulation code you have given assumes global coordinate system.
In other words, is there any requirement of the coordinate system used for the algorithm to work properly?

Thank you!

**Comment by yangshishan** [comment]
Hi, thank you for your interest in our work. There is no requirement for the coordinate system. If the sensor is mounted on a vehicle, the position of the sensor is normally taken as the origin.

**Comment by boazMgm** [comment]
Thanks!
